docker: Build from fedora minimal image instead
ModioAB/caramel-client pull request #2
Opened 2018-04-05 09:18 UTC by Spindel

This uses a minimal image rather than the modio python3 image.  Final build
gets a bit larger, so more work might be needed.

Issue: ModioAB/caramel-client#1

2018-04-05 09:51 UTC, teyrow commented
Broken. Entrypoint must be
/usr/local/bin/...
or just rely on path.

2018-04-05 09:52 UTC, teyrow requested changes
wrong path

2018-04-05 14:23 UTC, teyrow commented
Works fine on my Mac.

2018-04-06 10:06 UTC, niligulmohar approved these changes

2018-04-06 12:12 UTC, merged